version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  web_dev:
    build: .
    command: python shittybirthdaycards_com/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
